[package]
name = "trace-macro"
version = "0.2.0"
authors = ["DoumanAsh <custparasite@gmx.se>"]
description = "Simple trace macros"
repository = "https://github.com/DoumanAsh/trace-macro"
license = "MIT"
